version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
      - echo -n "$CODEBUILD_BUILD_ID" | sed "s/.*:\([[:xdigit:]]\{7\}\).*/\1/" > /tmp/build_id.out
      - echo BUILD-ID $(cat /tmp/build_id.out)
      - printf "%s:%s" "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME" "$(cat /tmp/build_id.out)" > /tmp/build_tag.out
      - printf '{"Tag":"%s"}' "$(cat /tmp/build_id.out)" > /tmp/build.json
      
  build:
    commands:
      - echo Build started on `date` with env
      - echo Building the Docker image...          
      - docker build --tag "$(cat /tmp/build_tag.out)" .     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - echo docker push "$(cat /tmp/build_tag.out)"
      - docker push "$(cat /tmp/build_tag.out)"
artifacts:
  files: /tmp/build.json
  discard-paths: yes
